@isTest
public class DeleteUAT13122023{
private Integer num;
    
    @isTest
   public static void helloMethod() {

        System.debug('Change Hello DemoApex11 Basic min8or change Pipeline testing in TEST Env 20/05/2024');
    //some additional changes done in feature branch

    }
    
    public static testMethod void testNewMethod() {
        System.debug('Change Hello DemoApex10 testing 1234 Basic ');
    }
}
