name: CI/CD Pipeline

on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Compiling the code
        run: |
          echo "Compiling the code..."
          RANDOM_NUMBER=$RANDOM
          echo $RANDOM_NUMBER
          echo ${{ secrets.FAIL_STAGE }}
          echo ${{ secrets.NO_FAIL }}
          if [ $(( RANDOM_NUMBER % 2 )) -eq 0 ] || [ "${{ secrets.FAIL_STAGE }}" == 'build' ] || [ "${{ secrets.NO_FAIL }}" == 'true' ]; then
            exit 1
          fi
          echo "Compile complete."
        continue-on-error: true

  unit-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Running unit tests
        run: |
          echo "Running unit tests... This will take about 60 seconds."
          sleep 10
          echo ${{ secrets.FAIL_STAGE }}
          echo "Code coverage is 90%"

  lint-test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Linting code
        run: |
          echo "Linting code... This will take about 10 seconds."
          sleep 5
          echo ${{ secrets.FAIL_STAGE }}
          echo "No lint issues found."

  mock-stage-1:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'
    steps:
      - name: Mock stage 1
        run: echo "Mock stage 1 Completed"

  dast-stage-1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: DAST stage 1
        run: |
          sleep 10
          echo "DAST stage 1 Completed"

  sast-stage-1:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: SAST stage 1
        run: |
          sleep 15
          if [ $(( $RANDOM % 6 )) == 0 ] || [ "${{ secrets.FAIL_STAGE }}" == 'sast' ] || [ "${{ secrets.NO_FAIL }}" == 'true' ]; then
            exit 1
          fi
          echo "SAST stage 1 Completed"

  deploy-dev:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    steps:
      - name: Deploy to dev
        run: |
          echo "Deploying application in dev"
          echo "Application successfully deployed in dev"

  deploy-prod:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Deploy to prod
        run: |
          echo "Deploying application to prod..."
          if [ "${{ secrets.FAIL_STAGE }}" == 'deploy' ]; then
            exit 1
          fi
          echo "Application successfully deployed to prod."

### Action Items:
- [ ] Add respective GitHub secrets to run workflow.
- [ ] Review manual trigger replacements.
- [ ] For features not supported by GitHub Actions, provide manual action steps to be taken.
